{% set version = "2.4.26" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rcompanion
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rcompanion_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rcompanion/rcompanion_{{ version }}.tar.gz
  sha256: 9a420d2ef95c3146d5d4f573581c41bca476df35f35d2d5a9817b22f5d6e95b1

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-desctools >=0.99.43
    - r-boot >=1.3_28
    - r-coin >=1.4_2
    - r-lmtest >=0.9_38
    - r-multcompview >=0.1_8
    - r-nortest >=1.0_4
    - r-plyr >=1.8.6
  run:
    - r-base
    - r-desctools >=0.99.43
    - r-boot >=1.3_28
    - r-coin >=1.4_2
    - r-lmtest >=0.9_38
    - r-multcompview >=0.1_8
    - r-nortest >=1.0_4
    - r-plyr >=1.8.6

test:
  commands:
    - $R -e "library('rcompanion')"           # [not win]
    - "\"%R%\" -e \"library('rcompanion')\""  # [win]

about:
  home: http://rcompanion.org/
  license: GPL-3.0-only
  summary: Functions and datasets to support "Summary and Analysis of Extension Program Evaluation in R" and "An R Companion for the Handbook of Biological Statistics". Vignettes are available at <http://rcompanion.org>.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: rcompanion
# Version: 2.3.7
# Date: 2019-09-28
# Title: Functions to Support Extension Education Program Evaluation
# Authors@R: c(person(given = "Salvatore", family = "Mangiafico", role = c("aut", "cre"), email = "mangiafico@njaes.rutgers.edu", comment = c(ORCID = "0000-0003-4668-6821")))
# Description: Functions and datasets to support "Summary and Analysis of Extension Program Evaluation in R" and "An R Companion for the Handbook of Biological Statistics". Vignettes are available at <http://rcompanion.org>.
# URL: http://rcompanion.org/
# Depends: R (>= 3.3.0)
# Imports: stats (>= 3.3.0), graphics (>= 3.3.0), boot (>= 1.3-18), DescTools (>= 0.99.17), multcompView (>= 0.1-7), plyr (>= 1.8.4), EMT (>= 1.1), coin (>= 1.1-2), lmtest (>= 0.9-34), nortest (>= 1.0-4)
# Suggests: FSA (>= 0.8.9)
# Maintainer: Salvatore Mangiafico <mangiafico@njaes.rutgers.edu>
# License: GPL-3
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-09-29 01:10:28 UTC; salma
# Author: Salvatore Mangiafico [aut, cre] (<https://orcid.org/0000-0003-4668-6821>)
# Repository: CRAN
# Date/Publication: 2019-09-29 16:00:06 UTC
