appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: fiBuQWlpBDGj6QVrYCVZ8SEuBh4m+yZRB9QxRMHT1nlJ4M4iC4HmPXOhQ/DhxAPbYqhCPH/jBUxYG+1rKkyhfcmuIYsqROncJXQka/FgjWgkCIhUp/gmyqtXdK6uQh0WNPYt6oqe0qkTY3O1+z+O1AZtKL8mRu+/uZ8D2xAI+ob2qhJckvMgqHgZT/Ailqjvk94BDEd1dErjNCOuT+Ubjt5lm2w5YP0YxbhnSVUVIXPCXS/1LT4gNZirTsmNG1CySxhajXPJJ50sosIGYQn7xhjmYv4T0eR0Mgs088Pz48QLlJ4rVmvGRrQBVPldQh0lcmy4PgbLCm2xw4z2UCgc87+pS5thmh5VAwaYGWuuVi6og3a7EOdICMJl+uHjhFrc/Bu+js/3/G0q90L+r4d+IBcdvQpVA7PP0Aazy7D9NbtJ/6DO7Y0uzLxE0qH/Tn3PizdoQeVXNw890JlB/EReaZXebDJKfsPjLy/NlE5PTRwoB06lEtXKMZjF51N7xWKYoULOmKXO1yNUf5lPInyd2QbZw/UOpb7I3N/8/v+n6ZXanD0JnsPr/Qixx3Al48935cksDutTbgDm814Twkc5EpvWcp9iiNrK9A20MCSxZZ4GHDD9BKjoxRsTBf9mYs6dqqWq8mwYEtDHguxr44uO3G+IDRGsmJWlaocduVeiLjY=
